In [1]:
import os
os.environ["JAX_PLATFORMS"] = "cpu"
os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=2"

import jax
import jax.numpy as jnp
from jax.sharding import Mesh, PartitionSpec as P, NamedSharding
from jax.experimental import mesh_utils

print("Devices =", jax.devices())
print("Device count =", jax.device_count())

global_devices = mesh_utils.create_device_mesh((jax.device_count(),))
MESH = Mesh(global_devices, axis_names=("devices",))
DEVICE_SPEC = P("devices")
REPLICATED_SPEC = P()
DEVICE_SHARDING = NamedSharding(MESH, P("devices"))
REPLICATED_SHARDING = NamedSharding(MESH, P())

jax.__version__
import jaxmg
import math
import jVMC_exp

Devices = [CpuDevice(id=0), CpuDevice(id=1)]
Device count = 2
Running in single-node mode (JVMC_USE_DISTRIBUTED not set)


In [9]:
A = jnp.ones((3))

jnp.pad(A, (0, 0))

Array([1., 1., 1.], dtype=float64)

Reshard a matrix from the existing 1D `DEVICE_SHARDING` (row-blocked across `m` devices) onto a genuine 2D block mesh, without ever materializing the full matrix on the host or on a single device, then hand it to `jaxmg.syevd`.

Works for any `m` and any `N` as long as `N % m == 0` (padding for the general case comes later).

# Simple Case EigDecomp

In [ ]:


def closest_factor_pair(m: int) -> tuple[int, int]:
    """Most-square-ish (p_rows, p_cols) with p_rows * p_cols == m."""
    p_rows = int(math.isqrt(m))
    while m % p_rows != 0:
        p_rows -= 1
    return p_rows, m // p_rows

def make_2d_mesh(num_devices: int, axis_names=("row", "col")) -> Mesh:
    p_rows, p_cols = closest_factor_pair(num_devices)
    devices_2d = mesh_utils.create_device_mesh((p_rows, p_cols))
    
    return Mesh(devices_2d, axis_names=axis_names)

def reshard_to_2d(A, mesh_2d: Mesh, axis_names=("row", "col")):
    row_axis, col_axis = axis_names
    
    return jax.device_put(A, NamedSharding(mesh_2d, P(row_axis, col_axis)))

In [ ]:
N = 253
A = jnp.eye(N)

m = jax.device_count()
pad_size = (-N) % m          # 0 when N is already divisible by m
N_padded = N + pad_size

# Push the pad_size extra eigenvalues to a location guaranteed to be outside
# A's real spectrum, whatever that spectrum is (including exact zeros or
# negative values): pad the corner block's diagonal with a constant c chosen
# strictly larger than any eigenvalue A could have, instead of zero-padding.
# This removes the earlier assumption that regularization keeps the real
# spectrum away from 0.
bound = jnp.linalg.norm(A)   # Frobenius norm >= spectral radius for Hermitian A
c = 2 * bound + 1

A_padded = jnp.pad(A, ((0, pad_size), (0, pad_size)), mode="constant")
pad_idx = jnp.arange(N, N_padded)
A_padded = A_padded.at[pad_idx, pad_idx].add(c)

assert N_padded % m == 0

A_padded = jax.device_put(A_padded, DEVICE_SHARDING)

MESH_2D = make_2d_mesh(m)
A_2d = reshard_to_2d(A_padded, MESH_2D)

p_rows, p_cols = MESH_2D.shape["row"], MESH_2D.shape["col"]
local_rows, local_cols = N_padded // p_rows, N_padded // p_cols
T_A = math.gcd(local_rows, local_cols)

print(f"N={N} padded to {N_padded} (+{pad_size}), {m} devices -> {p_rows}x{p_cols} grid, "
      f"local shard {(local_rows, local_cols)}, T_A={T_A}, pad diagonal c={c}")

eigenvalues, eigenvectors = jaxmg.syevd(A_2d, T_A, MESH_2D)

In [ ]:
# c was chosen strictly larger than any eigenvalue the real N x N block could
# have, so the pad_size fake eigenvalues (all == c) are provably the LARGEST
# in the spectrum -- the last pad_size entries in ascending order -- no
# matter what the real spectrum looks like, including genuine zeros or
# negative eigenvalues. There is no degenerate collision with the real
# spectrum by construction, so this separation is exact, not heuristic.
if pad_size > 0:
    assert jnp.allclose(eigenvalues[-pad_size:], c, atol=1e-6 * c)
    assert jnp.allclose(eigenvectors[:N, -pad_size:], 0.0, atol=1e-10)

eigenvalues = eigenvalues[:N]
eigenvectors = eigenvectors[:N, :N]

assert eigenvalues.shape == (N,)
assert eigenvectors.shape == (N, N)

# Grads

In [ ]:
L = 10
n_samples = 2**6
n_chains = 2**4
batch_size = n_samples

net = jVMC_exp.nets.CpxRBM(L)
psi = jVMC_exp.vqs.NQS(net, L, batch_size, seed=123)
sampler = jVMC_exp.sampler.MCSampler(
    psi,
    jVMC_exp.propose.SpinFlip(),
    123,
    n_chains,
    n_samples
)
sampler.sample()
grad = jVMC_exp.stats.SampledObs(psi.gradients(sampler.samples), sampler.weights)
grad_lazy = jVMC_exp.stats.LazySampledObs(psi.lazy_gradients(sampler.samples), sampler.weights)

print("# Parameters:", psi.numParameters)

from functools import partial

def remove_double(arr, params_shape):
    new_arr = []
    start = 0
    for s in params_shape:
        new_arr.append(arr[start:start + s[0]])
        start += 2 * s[0]
    
    return jnp.concatenate(new_arr)

if psi.holomorphic:
    grad.transform(jax.vmap(partial(remove_double, params_shape=psi.paramShapes)))

# Parameters: 100


In [41]:
def make_2d_mesh(axis_names=("row", "col")):
    num_devices = jax.device_count()

    p_rows = int(math.isqrt(num_devices))
    while num_devices % p_rows != 0:
        p_rows -= 1
    p_cols = num_devices // p_rows
    devices_2d = mesh_utils.create_device_mesh((p_rows, p_cols))
    
    return Mesh(devices_2d, axis_names=axis_names)

MESH_2D = make_2d_mesh(axis_names=("row", "col"))
DEVICE_SPEC_2D = P(("row", "col"))
DEVICE_SHARDING_2D = NamedSharding(MESH_2D, DEVICE_SPEC_2D)

In [51]:
from jVMC_exp.sharding_config import sharded

class Test(jVMC_exp.stats.SampledObs):
    def get_qgt(self):
        qgt = self._get_qgt(self._normalized_obs, batch_size=None)

        return jax.device_put(qgt, DEVICE_SHARDING_2D)

    @sharded(use_vmap=False)
    def _get_qgt(self, grad_log_psi, *, batch_size):
        local = jnp.tensordot(jnp.conj(grad_log_psi), grad_log_psi, axes=(0, 0))
        return jax.lax.psum_scatter(local, "devices", scatter_dimension=0, tiled=True)

In [ ]:
from jVMC_exp.stats import SampledObs, LazySampledObs

num_devices = jax.device_count()
pad_size = (- psi.numParameters) % num_devices

# TODO: in solve invert order of rhs and lhs otherwise you loose the mean
class Test(jVMC_exp.optimizer.SR):
    def _get_lhs_dense(self, grad_log_psi: SampledObs | LazySampledObs):
        '''
        Returns left hand side of the TDVP equation with shape (n_parameters, n_parameters).
        If n_parameters is not divisible by the number of devices, the output is padded.
        '''
        if pad_size != 0:
            grad_log_psi.transform(lambda x: jnp.pad(x, ((0, 0), (0, pad_size)), mode="constant"))
        
        if isinstance(grad_log_psi, SampledObs):
            S = self._get_qgt(grad_log_psi._centered_obs, batch_size=None)
        else:
            mean = 0
            S = 0
            for batch, weights in zip(grad_log_psi._observations, grad_log_psi._weights):
                batch, batch_mean = self._weight_and_mean(batch, weights, batch_size=None)
                mean += batch_mean
                S += self._get_qgt(batch, batch_size=None)
    
            S = S - jnp.tensordot(jnp.conj(mean), mean, axes=0)

        if pad_size != 0:
            grad_log_psi.transform(lambda x: x[:,:-pad_size])

        self._S0 = S[:-pad_size, :-pad_size]
        S = self._lhs_trans_fn(S)

        if self.diag_scale > 1e-15:
            S = S + jnp.diag(self.diag_scale * jnp.diag(S))
        if self.diag_shift > 1e-15:
            idx = jnp.arange(S.shape[0] - pad_size)
            S = S.at[idx, idx].add(self.diag_shift)

        return S

    @sharded(use_vmap=False)
    def _get_qgt(self, grad_log_psi, *, batch_size):
        """
        Return the quantum geometric tensor, sharded accross devices on the first axis.
        """
        local = jnp.tensordot(jnp.conj(grad_log_psi), grad_log_psi, axes=(0, 0))
    
        return jax.lax.psum_scatter(local, "devices", scatter_dimension=0, tiled=True)

    @sharded(use_vmap=False)
    def _weight_and_mean(self, batch, weights, *, batch_size):
        """
        Return the quantum geometric tensor, sharded accross devices on the first axis.
        """
        weighted_batch = jnp.einsum("i, i... -> i...", jnp.sqrt(weights), batch)
        mean = jax.lax.psum_scatter(
            jnp.tensordot(weights, batch, axes=(0, 0)), 
            "devices", 
            scatter_dimension=0, 
            tiled=True
        )

        return weighted_batch, mean

In [197]:
L = 3
n_samples = 4
n_chains = 2
batch_size = 2

net = jVMC_exp.nets.CpxRBM(L)
psi = jVMC_exp.vqs.NQS(net, 1, batch_size, seed=123)
sampler = jVMC_exp.sampler.MCSampler(
    psi,
    jVMC_exp.propose.SpinFlip(),
    123,
    n_chains,
    n_samples
)
sampler.sample()
grad = jVMC_exp.stats.SampledObs(psi.gradients(sampler.samples), sampler.weights)
grad_lazy = jVMC_exp.stats.LazySampledObs(psi.lazy_gradients(sampler.samples), sampler.weights)

print("# Parameters:", psi.numParameters)

from functools import partial

def remove_double(arr, params_shape):
    new_arr = []
    start = 0
    for s in params_shape:
        new_arr.append(arr[start:start + s[0]])
        start += 2 * s[0]
    
    return jnp.concatenate(new_arr)

if psi.holomorphic:
    grad.transform(jax.vmap(partial(remove_double, params_shape=psi.paramShapes)))
    grad_lazy.transform(jax.vmap(partial(remove_double, params_shape=psi.paramShapes)))

# Parameters: 3


In [202]:
opt = Test(sampler, psi)
opt_old = jVMC_exp.optimizer.SR(sampler, psi)

jnp.real(opt._get_lhs_dense(grad_lazy))

Array([[0.001, 0.   , 0.   , 0.   ],
       [0.   , 0.001, 0.   , 0.   ],
       [0.   , 0.   , 0.001, 0.   ],
       [0.   , 0.   , 0.   , 0.   ]], dtype=float64)

In [119]:
grad.transform(lambda x: jnp.pad(x, ((0, 0), (0, pad_size)), mode="constant"))

In [121]:
grad_lazy.transform(lambda x: jnp.pad(x, ((0, 0), (0, pad_size)), mode="constant"))

In [122]:
jnp.real(jnp.concatenate(list(grad_lazy.observations)))

Array([[0.00980858, 0.00951325, 0.00980858, 0.00951325, 0.        ],
       [0.00980858, 0.00951325, 0.00980858, 0.00951325, 0.        ],
       [0.00980858, 0.00951325, 0.00980858, 0.00951325, 0.        ],
       [0.00980858, 0.00951325, 0.00980858, 0.00951325, 0.        ]],      dtype=float64)

In [120]:
jnp.real(grad.observations)

Array([[0.00980858, 0.00951325, 0.00980858, 0.00951325, 0.        ],
       [0.00980858, 0.00951325, 0.00980858, 0.00951325, 0.        ],
       [0.00980858, 0.00951325, 0.00980858, 0.00951325, 0.        ],
       [0.00980858, 0.00951325, 0.00980858, 0.00951325, 0.        ]],      dtype=float64)

In [ ]:
num_devices = jax.device_count()
pad_size = (- psi.numParameters) % num_devices

def get_qgt(grad_obs):
    grad_obs = jnp.pad(grad_obs, ((0, 0), (0, pad_size)), mode="constant")
    local = jnp.tensordot(jnp.conj(grad_obs), grad_obs, axes=(0, 0))

    return jax.lax.psum_scatter(local, "devices", scatter_dimension=0, tiled=True)

get_qgt_sh = jax.jit(
    jax.shard_map(
        get_qgt,
        in_specs=DEVICE_SPEC,
        out_specs=DEVICE_SPEC,
        mesh=MESH
    )
)

grad_obs = grad.observations
qgt = get_qgt_sh(grad_obs)
# qgt_2d = jax.device_put(qgt, DEVICE_SHARDING_2D)

# qgt_2d.addressable_shards

# pad_idx = jnp.arange(N, N_padded)

[Shard(device=CpuDevice(id=0), index=(slice(0, 41, None), slice(None, None, None)), replica_id=0, data=[[0.0370638 +0.j         0.02571685-0.01193603j 0.02272357-0.00257957j
   ... 0.00419351-0.00515922j 0.01024337+0.00343079j
   0.        +0.j        ]
  [0.02571685+0.01193603j 0.0478205 +0.j         0.03035393+0.00643923j
   ... 0.00867441+0.00046111j 0.00927026+0.00947774j
   0.        +0.j        ]
  [0.02272357+0.00257957j 0.03035393-0.00643923j 0.03138147+0.j
   ... 0.00415546+0.00042304j 0.00640497+0.00543568j
   0.        +0.j        ]
  ...
  [0.00531668+0.00412034j 0.00731221-0.00033614j 0.00312282+0.j
   ... 0.01469212-0.00493575j 0.01813189+0.00068756j
   0.        +0.j        ]
  [0.01029688-0.00195848j 0.0094014 -0.00763464j 0.00389752-0.00601102j
   ... 0.02181261-0.01023931j 0.029422  -0.0044944j
   0.        +0.j        ]
  [0.00601531+0.00537219j 0.01001977-0.00065741j 0.0053338 -0.00013642j
   ... 0.01803625-0.00483466j 0.02189008+0.001613j
   0.        +0.j        ]

In [171]:
A = jax.device_put(jnp.ones((2, 4)), DEVICE_SHARDING)
w = jax.device_put(jnp.ones(2), DEVICE_SHARDING)
# A = jnp.tensordot(w, A, axes=(0, 0))
pad_size = 2
A = jnp.pad(A, ((0, 0), (0, pad_size)), mode="constant")

A[:,:-pad_size]

Array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float64)

In [205]:
A = jax.device_put(jnp.ones((2, 4)), DEVICE_SHARDING)

A.addressable_shards

[Shard(device=CpuDevice(id=0), index=(slice(0, 1, None), slice(None, None, None)), replica_id=0, data=[[1. 1. 1. 1.]]),
 Shard(device=CpuDevice(id=1), index=(slice(1, 2, None), slice(None, None, None)), replica_id=0, data=[[1. 1. 1. 1.]])]

In [214]:
A.at[0,0].set(2).addressable_shards

[Shard(device=CpuDevice(id=0), index=(slice(0, 1, None), slice(None, None, None)), replica_id=0, data=[[2. 1. 1. 1.]]),
 Shard(device=CpuDevice(id=1), index=(slice(1, 2, None), slice(None, None, None)), replica_id=0, data=[[1. 1. 1. 1.]])]