In [1]:
from __future__ import annotations
import jax
import jax.numpy as jnp
from functools import partial

from jVMC_exp.sharding_config import DEVICE_SHARDING, MESH


An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


Running in single-node mode (JVMC_USE_DISTRIBUTED not set)


In [13]:
class test():
    def __init__(self, x):
        self.x = jax.device_put(x, DEVICE_SHARDING, donate=True)

x = jnp.ones(12)
cls = test(x)

print(x)
print(cls.x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
cls.x

Array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float64)