In [3]:
import os
os.environ["JAX_PLATFORMS"] = "cpu"
os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=2"

import jax
import jax.numpy as jnp
from jax.sharding import Mesh, PartitionSpec as P, NamedSharding
from jax.experimental import mesh_utils

print("Devices =", jax.devices())
print("Device count =", jax.device_count())

global_devices = mesh_utils.create_device_mesh((jax.device_count(),))
MESH = Mesh(global_devices, axis_names=("devices",))
DEVICE_SPEC = P("devices")
REPLICATED_SPEC = P()
DEVICE_SHARDING = NamedSharding(MESH, P("devices"))
REPLICATED_SHARDING = NamedSharding(MESH, P())

jax.__version__

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


Devices = [CpuDevice(id=0), CpuDevice(id=1)]
Device count = 2


'0.10.1'

In [4]:
import jaxmg

In [ ]:
A = jnp.ones((256, 256))

A = jax.device_put(A, DEVICE_SHARDING)

res = jaxmg.syevd(A, )

[Shard(device=CpuDevice(id=0), index=(slice(0, 128, None), slice(None, None, None)), replica_id=0, data=[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]),
 Shard(device=CpuDevice(id=1), index=(slice(128, 256, None), slice(None, None, None)), replica_id=0, data=[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]])]